"""Add day of week column to activity_plan

Revision ID: 1f958fc1eaa1
Revises: 4cddd0774cd2
Create Date: 2024-09-19 19:43:55.191204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f958fc1eaa1'
down_revision = '4cddd0774cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_plan', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
