"""Initial migration

Revision ID: 4cddd0774cd2
Revises: 
Create Date: 2024-09-19 19:24:21.126780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cddd0774cd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('morning', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('evening', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bmi_category', sa.String(length=20), nullable=True))
        batch_op.drop_column('morning_activity')
        batch_op.drop_column('evening_activity')
        batch_op.drop_column('afternoon_activity')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('afternoon_activity', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('evening_activity', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('morning_activity', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('bmi_category')
        batch_op.drop_column('evening')
        batch_op.drop_column('morning')

    # ### end Alembic commands ###
